
export enum OtpMediumEnum {
    SMS='SMS',
    EMAIL='EMAIL',
    WHATSAPP='WHATSAPP'
}

export enum OtpPurposeEnum {
    RESET_PASSWORD='RESET_PASSWORD',
    VERIFY_ACCOUNT='VERIFY_ACCOUNT',
    OTP_VERIFICATION='OTP_VERIFICATION',
}
